<?php
defined('ABSPATH') || exit;

/** Lightweight runtime translations keyed to the WordPress site language. */
final class WhisperLink_I18n {
    private static function language(): string {
        $locale = (string) get_option('WPLANG', '');
        if ($locale === '') $locale = function_exists('get_locale') ? (string) get_locale() : 'en_US';
        $code = strtolower(substr($locale, 0, 2));
        return in_array($code, ['ar', 'fr', 'en'], true) ? $code : 'en';
    }

    public static function lang(): string { return self::language(); }
    public static function dir(): string { return self::language() === 'ar' ? 'rtl' : 'ltr'; }

    private static function php_text(): array {
        return [
            'الروابط الداخلية' => ['en' => 'Internal links', 'fr' => 'Liens internes'],
            'يتطلب WhisperLink امتداد PHP mbstring.' => ['en' => 'WhisperLink requires the PHP mbstring extension.', 'fr' => 'WhisperLink nécessite l’extension PHP mbstring.'],
            'لا تملك صلاحية تعديل هذه الصفحة أو أنها خارج نطاق الفحص.' => ['en' => 'You cannot edit this page, or it is outside the scan scope.', 'fr' => 'Vous ne pouvez pas modifier cette page, ou elle est hors du périmètre d’analyse.'],
            'تعديل محتوى منشئ الصفحات غير مدعوم في هذا الإصدار.' => ['en' => 'Page-builder content editing is not supported in this version.', 'fr' => 'La modification du contenu des constructeurs de pages n’est pas prise en charge dans cette version.'],
            'الصفحة مفتوحة للتعديل بواسطة مستخدم آخر.' => ['en' => 'Another user is editing this page.', 'fr' => 'Cette page est en cours de modification par un autre utilisateur.'],
            'توجد عملية تعديل أخرى لهذا المقال. أعد المحاولة بعد قليل.' => ['en' => 'Another update is running for this post. Try again shortly.', 'fr' => 'Une autre modification est en cours pour cet article. Réessayez dans un instant.'],
            'تغير المحتوى. حدّث الاقتراحات قبل المحاولة مجددًا.' => ['en' => 'The content changed. Refresh the suggestions before trying again.', 'fr' => 'Le contenu a changé. Actualisez les suggestions avant de réessayer.'],
            'تعذر حفظ نسخة التراجع، لم يتغير المحتوى.' => ['en' => 'The undo copy could not be saved, so the content was not changed.', 'fr' => 'La copie d’annulation n’a pas pu être enregistrée ; le contenu n’a pas été modifié.'],
            'غير مصرح.' => ['en' => 'Unauthorized.', 'fr' => 'Non autorisé.'],
            'طلب غير صالح.' => ['en' => 'Invalid request.', 'fr' => 'Requête invalide.'],
            'وجهة غير صالحة.' => ['en' => 'Invalid destination.', 'fr' => 'Destination invalide.'],
            'تغير المقال. أعد توليد الاقتراحات.' => ['en' => 'The post changed. Generate the suggestions again.', 'fr' => 'L’article a changé. Générez à nouveau les suggestions.'],
            'يوجد رابط لهذه الوجهة بالفعل.' => ['en' => 'A link to this destination already exists.', 'fr' => 'Un lien vers cette destination existe déjà.'],
            'نص الرابط غير صالح.' => ['en' => 'Invalid anchor text.', 'fr' => 'Texte d’ancrage invalide.'],
            'كل قاعدة تحتاج عبارة من 3–120 حرفًا ورقم صفحة منشورة ضمن النطاق.' => ['en' => 'Each rule needs a 3–120 character phrase and an in-scope published page ID.', 'fr' => 'Chaque règle nécessite une expression de 3 à 120 caractères et l’ID d’une page publiée incluse dans le périmètre.'],
            'تغير المقال. أعد المعاينة.' => ['en' => 'The post changed. Preview again.', 'fr' => 'L’article a changé. Relancez l’aperçu.'],
            'تغيرت القواعد أو الإعدادات. أعد المعاينة.' => ['en' => 'Rules or settings changed. Preview again.', 'fr' => 'Les règles ou les réglages ont changé. Relancez l’aperçu.'],
            'السجل غير متاح.' => ['en' => 'The history record is unavailable.', 'fr' => 'L’entrée d’historique n’est pas disponible.'],
            'يوجد تعديل أحدث. تراجع عنه أولًا، أو استخدم مراجعات ووردبريس.' => ['en' => 'A newer edit exists. Undo it first, or use WordPress revisions.', 'fr' => 'Une modification plus récente existe. Annulez-la d’abord ou utilisez les révisions WordPress.'],
            'اختر نوع محتوى واحدًا على الأقل.' => ['en' => 'Select at least one content type.', 'fr' => 'Sélectionnez au moins un type de contenu.'],
            'عملية غير معروفة.' => ['en' => 'Unknown operation.', 'fr' => 'Opération inconnue.'],
            'أدخل عنوان HTTP أو HTTPS كاملًا.' => ['en' => 'Enter a complete HTTP or HTTPS URL.', 'fr' => 'Saisissez une URL HTTP ou HTTPS complète.'],
            'تقارير الروابط متاحة لمدير الموقع.' => ['en' => 'Link reports are available to site administrators.', 'fr' => 'Les rapports de liens sont disponibles pour les administrateurs du site.'],
            'احفظ المقال ثم افتح الاقتراحات لمراجعة الروابط.' => ['en' => 'Save the post, then open suggestions to review links.', 'fr' => 'Enregistrez l’article, puis ouvrez les suggestions pour vérifier les liens.'],
            'اقتراح روابط لهذا المقال' => ['en' => 'Suggest links for this post', 'fr' => 'Suggérer des liens pour cet article'],
            'روابط أفضل، محتوى مترابط.' => ['en' => 'Better links, connected content.', 'fr' => 'De meilleurs liens, un contenu bien connecté.'],
            'راجع فرص الربط الداخلي، أصلح الروابط وتابع تغطية صفحاتك.' => ['en' => 'Review internal-link opportunities, repair links, and track page coverage.', 'fr' => 'Examinez les opportunités de liens internes, corrigez les liens et suivez la couverture des pages.'],
            'فحص المحتوى' => ['en' => 'Scan content', 'fr' => 'Analyser le contenu'],
            'أقسام الإضافة' => ['en' => 'Plugin sections', 'fr' => 'Sections de l’extension'],
            'جارٍ التحميل…' => ['en' => 'Loading…', 'fr' => 'Chargement…'],
            'الاقتراحات تعتمد على تطابق الكلمات والتشابه النصي المحلي. افحص ملاءمة السياق قبل الإدراج.' => ['en' => 'Suggestions use keyword matches and local text similarity. Check the context before inserting.', 'fr' => 'Les suggestions reposent sur les mots-clés et la similarité textuelle locale. Vérifiez le contexte avant l’insertion.'],
        ];
    }

    public static function t(string $source): string {
        if (self::language() === 'ar') return $source;
        $row = self::php_text()[$source] ?? null;
        return $row[self::language()] ?? $row['en'] ?? $source;
    }

    public static function js(): array {
        $fr = [
            'تعذر قراءة استجابة الخادم. أعد تحميل الصفحة وتحقق من جلسة الدخول.'=>'Impossible de lire la réponse du serveur. Rechargez la page et vérifiez votre session.', 'تعذر تنفيذ الطلب.'=>'Impossible d’exécuter la demande.', 'لا توجد نتائج في هذه الصفحة.'=>'Aucun résultat sur cette page.',
            'السابق'=>'Précédent','التالي'=>'Suivant',' الصفحة '=>' Page ','تصدير النتائج المعروضة CSV'=>'Exporter les résultats affichés en CSV','نظرة عامة'=>'Vue d’ensemble','اقتراحات الربط'=>'Suggestions de liens','فحص الروابط'=>'Vérification des liens','النطاقات'=>'Domaines','الربط التلقائي'=>'Liens automatiques','تغيير العناوين'=>'Remplacement d’URL','سجل التعديلات'=>'Historique','الإعدادات'=>'Réglages','جارٍ تحميل البيانات…'=>'Chargement des données…',
            'صفحات مفهرسة'=>'Pages indexées','روابط في المحتوى'=>'Liens dans le contenu','صفحات يتيمة'=>'Pages orphelines','تغطية بروابط واردة'=>'Couverture par liens entrants','أخطاء 404 / 410'=>'Erreurs 404 / 410','خريطة الروابط في المحتوى'=>'Carte des liens du contenu','الروابط الواردة محسوبة من صفحات أخرى مفهرسة. لا يشمل الفحص القوائم والقوالب والمحتوى المخزن في منشئات الصفحات.'=>'Les liens entrants sont comptés depuis d’autres pages indexées. L’analyse exclut les menus, modèles et contenus stockés dans les constructeurs de pages.','بحث بالعنوان'=>'Rechercher par titre','ابحث عن مقال…'=>'Rechercher un article…','تصفية'=>'Filtrer','جميع الصفحات'=>'Toutes les pages','الصفحات اليتيمة'=>'Pages orphelines','بلا روابط داخلية صادرة'=>'Sans lien interne sortant','بحث'=>'Rechercher','اقتراحات'=>'Suggestions','الرقم'=>'ID','الصفحة'=>'Page','مصادر واردة'=>'Sources entrantes','داخلية صادرة'=>'Liens internes sortants','خارجية'=>'Externes','الإجراء'=>'Action',
            'الفحص مستمر: تمت مراجعة '=>'Analyse en cours : ',' سجلًا. اضغط فحص المحتوى لإكماله في هذه الجلسة.'=>' éléments examinés. Cliquez sur Analyser le contenu pour terminer dans cette session.','فرص ربط قابلة للمراجعة'=>'Opportunités de liens à vérifier','بحث محلي في أحدث 500 صفحة مفهرسة؛ يعرض حتى 40 اقتراحًا. الدرجة تقيس تشابه الكلمات وليست تقييم ذكاء اصطناعي.'=>'Recherche locale dans les 500 dernières pages indexées, avec jusqu’à 40 suggestions. Le score mesure la similarité des mots, pas une évaluation par IA.','رقم المقال'=>'ID de l’article','اتجاه الروابط'=>'Sens des liens','من المقال إلى صفحات أخرى'=>'De l’article vers d’autres pages','من صفحات أخرى إلى المقال'=>'D’autres pages vers l’article','الكلمات المفتاحية المستهدفة للمقال'=>'Mots-clés cibles de l’article','عبارات مفصولة بفواصل. تُقرأ أيضًا كلمات Yoast وRank Math تلقائيًا. الحفظ يستبدل الكلمات اليدوية السابقة.'=>'Expressions séparées par des virgules. Les mots-clés Yoast et Rank Math sont également lus. L’enregistrement remplace les mots-clés manuels précédents.','كلمات مفتاحية'=>'Mots-clés','حفظ الكلمات'=>'Enregistrer les mots-clés','تم حفظ الكلمات.'=>'Mots-clés enregistrés.','توليد الاقتراحات'=>'Générer les suggestions','لا توجد عبارات مطابقة قابلة للربط. أضف كلمات مستهدفة للصفحات وتأكد من اكتمال الفهرسة.'=>'Aucune expression correspondante à lier. Ajoutez des mots-clés cibles et vérifiez que l’indexation est terminée.','تشابه نصي '=>'Similarité textuelle ','نص الرابط'=>'Texte d’ancrage','إدراج الرابط'=>'Insérer le lien','أُدرج الرابط. أعد توليد الاقتراحات قبل تعديل المقال نفسه مجددًا.'=>'Lien inséré. Générez à nouveau les suggestions avant une autre modification de l’article.','لم يُعثر على نص قابل للربط بهذه العبارة.'=>'Aucun texte pouvant être lié avec cette expression.',
            'فحص صحة الروابط'=>'Vérification de l’état des liens','الفحص يطلب 3 عناوين في كل دفعة؛ النتائج تُخزّن 7 أيام. أخطاء الشبكة و403 و429 لا تعني بالضرورة أن الرابط مكسور. الفحص الخارجي اختياري في الإعدادات.'=>'L’analyse vérifie 3 URL par lot et conserve les résultats pendant 7 jours. Les erreurs réseau, 403 et 429 ne signifient pas forcément qu’un lien est cassé. La vérification externe est facultative.','فحص الدفعة التالية'=>'Vérifier le lot suivant','تم فحص '=>'URL vérifiées : ',' عناوين.'=>'','عرض الكل'=>'Tout afficher','عرض الأخطاء'=>'Afficher les erreurs','المقال'=>'Article','العنوان'=>'URL','النوع'=>'Type','آخر فحص'=>'Dernière vérification','داخلي'=>'Interne','خارجي'=>'Externe','لم يُفحص'=>'Non vérifié','خطأ اتصال'=>'Erreur de connexion','توزيع الروابط حسب النطاق — حتى 200 نطاق'=>'Répartition des liens par domaine — jusqu’à 200 domaines','النطاق'=>'Domaine','الروابط'=>'Liens','الصفحات المصدر'=>'Pages sources',
            'قواعد الربط بالكلمات المفتاحية'=>'Règles de liaison par mots-clés','عبارة واحدة ووجهة لكل سطر. مثال: تحسين محركات البحث | 42. يُضاف رابط واحد لكل وجهة، مع حد الروابط المحدد في الإعدادات.'=>'Une expression et une destination par ligne. Exemple : équipement camping | 42. Un lien est ajouté par destination, dans la limite définie dans les réglages.','قواعد الربط'=>'Règles de liaison','تطبيق على مقال موجود'=>'Appliquer à un article existant','حفظ القواعد'=>'Enregistrer les règles','صيغة القاعدة: العبارة | رقم الصفحة'=>'Format : expression | ID de page','حُفظت القواعد.'=>'Règles enregistrées.','معاينة القواعد'=>'Prévisualiser les règles','العبارة'=>'Expression','رقم الوجهة'=>'ID de destination','تطبيق الروابط المعروضة'=>'Appliquer les liens affichés','تم تطبيق القواعد وتسجيل نسخة للتراجع.'=>'Règles appliquées et copie d’annulation enregistrée.',
            'تغيير عنوان داخل الروابط'=>'Remplacer une URL dans les liens','مطابقة العنوان كاملًا مع الاحتفاظ بجزء #fragment. تعرض المعاينة أول 100 مقال متأثر؛ أعد المعاينة بعد تنفيذ الدفعة.'=>'Correspondance sur l’URL complète en conservant le fragment #. L’aperçu affiche les 100 premiers articles affectés ; relancez-le après chaque lot.','العنوان القديم'=>'Ancienne URL','العنوان الجديد'=>'Nouvelle URL','معاينة التغييرات'=>'Prévisualiser les modifications','تطبيق على هذا المقال'=>'Appliquer à cet article','تم تغيير الرابط.'=>'Lien modifié.','لا توجد تغييرات.'=>'Aucune modification.',
            'سجل التعديلات والتراجع'=>'Historique des modifications et annulation','يُرفض التراجع إذا تغير المحتوى بعد العملية. تبقى الروابط وسجلات التراجع بعد تعطيل الإضافة.'=>'L’annulation est refusée si le contenu a changé depuis l’opération. Les liens et l’historique restent après la désactivation de l’extension.','السجل'=>'Entrée','المستخدم'=>'Utilisateur','العملية'=>'Opération','التاريخ UTC'=>'Date UTC','تم التراجع'=>'Annulé','تراجع'=>'Annuler','تم استرجاع المحتوى.'=>'Contenu restauré.','اقتراح رابط'=>'Suggestion de lien','تغيير عنوان'=>'Remplacement d’URL',
            'نطاق الفحص والربط'=>'Périmètre d’analyse et de liaison','أنواع المحتوى المنشور'=>'Types de contenu publiés','أرقام الصفحات المستثناة'=>'IDs des pages exclues','أقصى روابط من القواعد لكل تطبيق'=>'Nombre maximal de liens par application','تطبيق القواعد عند حفظ مدير الموقع لمقال منشور'=>'Appliquer les règles lorsqu’un administrateur enregistre un article publié','فحص الروابط الخارجية: يرسل طلبات HTTP للنطاقات المشار إليها'=>'Vérifier les liens externes : envoie des requêtes HTTP aux domaines liés','لا تُرسل النصوص إلى خدمات ذكاء اصطناعي. الفحص الدوري يعتمد على WP-Cron وزيارات الموقع. بعد تغيير النطاق، شغّل فحص المحتوى من جديد.'=>'Aucun texte n’est envoyé à un service d’IA. L’analyse périodique dépend de WP-Cron et des visites. Après un changement de périmètre, relancez l’analyse.','حفظ الإعدادات'=>'Enregistrer les réglages','تم حفظ الإعدادات.'=>'Réglages enregistrés.','جارٍ فحص المحتوى: '=>'Analyse du contenu : ',' سجلًا…'=>' éléments…','اكتمل الفحص: '=>'Analyse terminée : ',' سجلًا تمت مراجعته.'=>' éléments examinés.'
        ];
        $en = [
            'تعذر قراءة استجابة الخادم. أعد تحميل الصفحة وتحقق من جلسة الدخول.'=>'Could not read the server response. Reload the page and check your session.','تعذر تنفيذ الطلب.'=>'The request could not be completed.','لا توجد نتائج في هذه الصفحة.'=>'No results on this page.','السابق'=>'Previous','التالي'=>'Next',' الصفحة '=>' Page ','تصدير النتائج المعروضة CSV'=>'Export displayed results as CSV','نظرة عامة'=>'Overview','اقتراحات الربط'=>'Link suggestions','فحص الروابط'=>'Link checks','النطاقات'=>'Domains','الربط التلقائي'=>'Auto-linking','تغيير العناوين'=>'URL changer','سجل التعديلات'=>'History','الإعدادات'=>'Settings','جارٍ تحميل البيانات…'=>'Loading data…',
            'صفحات مفهرسة'=>'Indexed pages','روابط في المحتوى'=>'Content links','صفحات يتيمة'=>'Orphan pages','تغطية بروابط واردة'=>'Inbound-link coverage','أخطاء 404 / 410'=>'404 / 410 errors','خريطة الروابط في المحتوى'=>'Content link map','الروابط الواردة محسوبة من صفحات أخرى مفهرسة. لا يشمل الفحص القوائم والقوالب والمحتوى المخزن في منشئات الصفحات.'=>'Inbound links are counted from other indexed pages. Menus, templates, and page-builder storage are excluded.','بحث بالعنوان'=>'Search by title','ابحث عن مقال…'=>'Search for a post…','تصفية'=>'Filter','جميع الصفحات'=>'All pages','الصفحات اليتيمة'=>'Orphan pages','بلا روابط داخلية صادرة'=>'No outgoing internal links','بحث'=>'Search','اقتراحات'=>'Suggestions','الرقم'=>'ID','الصفحة'=>'Page','مصادر واردة'=>'Inbound sources','داخلية صادرة'=>'Outgoing internal','خارجية'=>'External','الإجراء'=>'Action',
            'الفحص مستمر: تمت مراجعة '=>'Scan in progress: ',' سجلًا. اضغط فحص المحتوى لإكماله في هذه الجلسة.'=>' items reviewed. Click Scan content to finish in this session.','فرص ربط قابلة للمراجعة'=>'Reviewable link opportunities','بحث محلي في أحدث 500 صفحة مفهرسة؛ يعرض حتى 40 اقتراحًا. الدرجة تقيس تشابه الكلمات وليست تقييم ذكاء اصطناعي.'=>'Local search across the latest 500 indexed pages, showing up to 40 suggestions. The score measures word similarity, not an AI assessment.','رقم المقال'=>'Post ID','اتجاه الروابط'=>'Link direction','من المقال إلى صفحات أخرى'=>'From the post to other pages','من صفحات أخرى إلى المقال'=>'From other pages to the post','الكلمات المفتاحية المستهدفة للمقال'=>'Post target keywords','عبارات مفصولة بفواصل. تُقرأ أيضًا كلمات Yoast وRank Math تلقائيًا. الحفظ يستبدل الكلمات اليدوية السابقة.'=>'Comma-separated phrases. Yoast and Rank Math keywords are also read automatically. Saving replaces prior manual keywords.','كلمات مفتاحية'=>'Keywords','حفظ الكلمات'=>'Save keywords','تم حفظ الكلمات.'=>'Keywords saved.','توليد الاقتراحات'=>'Generate suggestions','لا توجد عبارات مطابقة قابلة للربط. أضف كلمات مستهدفة للصفحات وتأكد من اكتمال الفهرسة.'=>'No matching phrases available to link. Add target keywords and ensure indexing is complete.','تشابه نصي '=>'Text similarity ','نص الرابط'=>'Anchor text','إدراج الرابط'=>'Insert link','أُدرج الرابط. أعد توليد الاقتراحات قبل تعديل المقال نفسه مجددًا.'=>'Link inserted. Generate suggestions again before editing the post again.','لم يُعثر على نص قابل للربط بهذه العبارة.'=>'No linkable text was found for this phrase.',
            'فحص صحة الروابط'=>'Link health check','الفحص يطلب 3 عناوين في كل دفعة؛ النتائج تُخزّن 7 أيام. أخطاء الشبكة و403 و429 لا تعني بالضرورة أن الرابط مكسور. الفحص الخارجي اختياري في الإعدادات.'=>'The checker requests 3 URLs per batch and stores results for 7 days. Network, 403, and 429 errors do not necessarily mean a link is broken. External checking is optional.','فحص الدفعة التالية'=>'Check next batch','تم فحص '=>'Checked ',' عناوين.'=>' URLs.','عرض الكل'=>'Show all','عرض الأخطاء'=>'Show errors','المقال'=>'Post','العنوان'=>'URL','النوع'=>'Type','آخر فحص'=>'Last checked','داخلي'=>'Internal','خارجي'=>'External','لم يُفحص'=>'Not checked','خطأ اتصال'=>'Connection error','توزيع الروابط حسب النطاق — حتى 200 نطاق'=>'Links by domain — up to 200 domains','النطاق'=>'Domain','الروابط'=>'Links','الصفحات المصدر'=>'Source pages',
            'قواعد الربط بالكلمات المفتاحية'=>'Keyword auto-linking rules','عبارة واحدة ووجهة لكل سطر. مثال: تحسين محركات البحث | 42. يُضاف رابط واحد لكل وجهة، مع حد الروابط المحدد في الإعدادات.'=>'One phrase and destination per line. Example: camping equipment | 42. One link is added per destination, up to the limit in Settings.','قواعد الربط'=>'Linking rules','تطبيق على مقال موجود'=>'Apply to an existing post','حفظ القواعد'=>'Save rules','صيغة القاعدة: العبارة | رقم الصفحة'=>'Format: phrase | page ID','حُفظت القواعد.'=>'Rules saved.','معاينة القواعد'=>'Preview rules','العبارة'=>'Phrase','رقم الوجهة'=>'Destination ID','تطبيق الروابط المعروضة'=>'Apply displayed links','تم تطبيق القواعد وتسجيل نسخة للتراجع.'=>'Rules applied and an undo copy was recorded.',
            'تغيير عنوان داخل الروابط'=>'Change a URL in links','مطابقة العنوان كاملًا مع الاحتفاظ بجزء #fragment. تعرض المعاينة أول 100 مقال متأثر؛ أعد المعاينة بعد تنفيذ الدفعة.'=>'Matches the complete URL while preserving the #fragment. The preview shows the first 100 affected posts; preview again after each batch.','العنوان القديم'=>'Old URL','العنوان الجديد'=>'New URL','معاينة التغييرات'=>'Preview changes','تطبيق على هذا المقال'=>'Apply to this post','تم تغيير الرابط.'=>'Link changed.','لا توجد تغييرات.'=>'No changes.',
            'سجل التعديلات والتراجع'=>'Change history and undo','يُرفض التراجع إذا تغير المحتوى بعد العملية. تبقى الروابط وسجلات التراجع بعد تعطيل الإضافة.'=>'Undo is refused if content changed after the operation. Links and undo history remain after deactivation.','السجل'=>'Record','المستخدم'=>'User','العملية'=>'Operation','التاريخ UTC'=>'UTC date','تم التراجع'=>'Undone','تراجع'=>'Undo','تم استرجاع المحتوى.'=>'Content restored.','اقتراح رابط'=>'Link suggestion','تغيير عنوان'=>'URL replacement',
            'نطاق الفحص والربط'=>'Scan and linking scope','أنواع المحتوى المنشور'=>'Published content types','أرقام الصفحات المستثناة'=>'Excluded page IDs','أقصى روابط من القواعد لكل تطبيق'=>'Maximum rule links per run','تطبيق القواعد عند حفظ مدير الموقع لمقال منشور'=>'Apply rules when a site administrator saves a published post','فحص الروابط الخارجية: يرسل طلبات HTTP للنطاقات المشار إليها'=>'Check external links: sends HTTP requests to linked domains','لا تُرسل النصوص إلى خدمات ذكاء اصطناعي. الفحص الدوري يعتمد على WP-Cron وزيارات الموقع. بعد تغيير النطاق، شغّل فحص المحتوى من جديد.'=>'Text is not sent to AI services. Scheduled scans depend on WP-Cron and site visits. Scan content again after changing scope.','حفظ الإعدادات'=>'Save settings','تم حفظ الإعدادات.'=>'Settings saved.','جارٍ فحص المحتوى: '=>'Scanning content: ',' سجلًا…'=>' items…','اكتمل الفحص: '=>'Scan complete: ',' سجلًا تمت مراجعته.'=>' items reviewed.'
        ];
        return self::language() === 'fr' ? $fr : (self::language() === 'en' ? $en : []);
    }
}
